version: '3'
services:

  laravel-docker:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel-api
    image: agucomba/laravel-api:1.8
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
      
  mysql:
    container_name: mysql-laravel-api
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin-laravel-api
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    links:
      - mysql